apiVersion: v1
kind: Service
metadata:
  name: weather-station
  namespace: weather-monitoring
spec:
  clusterIP: None
  selector:
    app: weather-station
  ports:
    - name: dummy
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weather-station
  namespace: weather-monitoring
spec:
  serviceName: weather-station
  replicas: 10
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: weather-station
          image: weather-station:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "96Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
